### ISSUE TITLE
Personal app page issue

### ISSUE THREAD

**Issue by erinlessard** [tyler274/Recruitment-App#28]
[23:43:00] Jasmine Zamayaid > I applied on your website. However, when I click the blue eye on the Personal Applications it just refreshes the page.

**Comment by tyler274** [comment]
Works fine for me, will need to do some more intensive testing later.

**Comment by erinlessard** [comment]
Multiple people are commenting on this in kf_public, so it's a real issue.

**Comment by erinlessard** [comment]
This appears to occur for any account without recruiter roles. I made a new account and tried it, and upon clicking "view application" I was simply redirected to the applications page again. I cannot view the application directly as well - it just redirects to the applications page.

**Comment by tyler274** [comment]
Two things were leading to this
1. I was comparing by an application's id not the application's user id, to the user's id
2. two integers were being compared (I'm pretty sure) but the typing went weird, anyway its fixed by an explicit cast to int before the comparison. 

pushing to live on next update
